# Python script to define global variables for the application

import string

# Programm Version
__version__ = "0.1.0"

__alphabet__ = string.printable
# "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

# Pause between each letter
__text_sleep__ = 1 / 600

# Time between each module
# 1 / __module_time__
__module_time__ = 20
# Installer Modules
__modules__ = [
    "Loading kernel injector",
    "Installing GPU Shader Patcher",
    "Applying DirectX Optimizer",
    "Compiling Pixel Mesh Engine",
    "Activating Driver Supervisor",
    "Updating Render Context",
    "Injecting Frame Hook",
    "Scanning Bus Architecture",
    "Deploying Audio Bus Mapper",
    "Mounting Virtual Framebuffer",
    "Patching Vulkan Loader",
    "Syncing RT Shader Units",
    "Verifying Binary Cache",
    "Downloading Runtime Layers",
    "Configuring Thread Balancer",
    "Allocating VRAM Blocks",
    "Emulating PCI Bridge",
    "Generating Entropy Map",
    "Linking Resource Binder",
    "Parsing GPU Microcode",
    "Binding Port Services",
    "Spawning Device Monitor",
    "Unpacking Driver Assets",
    "Rewriting Boot Entry",
    "Building DirectCompute API",
    "Streaming Instruction Cache",
    "Encrypting Shader Trees",
    "Deploying 3D Pipeline",
    "Starting Render Loop",
    "Checking Fan Curve Table",
    "Loading Deep Buffer Stack",
    "Authenticating License Key",
    "Fetching OpenGL Fallback",
    "Resolving Display Endpoints",
    "Updating Mesh Layer Cache",
    "Validating Interface Token",
    "Seeding Secure RNG",
    "Warming up PCIe lanes",
    "Installing Anti-Aliasing Filter",
    "Injecting Diagnostic Layer",
    "Spooling PhysX Runtime",
    "Registering Callback Hooks",
    "Flashing BIOS Overlay",
    "Remapping Interrupt Vectors",
    "Optimizing Memory Lanes",
    "Injecting Overclock Preset",
    "Unpacking Animation Pack",
    "Loading Frame Debugger",
    "Deploying Scene Graph",
    "Building LUT Library",
    "Mounting /dev/graphics",
    "Rebuilding Textures Index",
    "Adjusting Gamma Curves",
    "Overriding Thermal Policy",
    "Cloning Render Presets",
    "Embedding Color Profile",
    "Installing Legacy Drivers",
    "Preloading Icon Set",
    "Tuning Shader Cores",
    "Launching Heat Sync Daemon",
    "Writing Output Pipeline",
    "Scaling TDP Limits",
    "Analyzing IO Map",
    "Compiling Device Tree",
    "Configuring Cache Policies",
    "Resolving Bus Topology",
    "Creating Swap Partitions",
    "Hashing Memory Pools",
    "Installing NetRender Bridge",
    "Patching DX12 Extensions",
    "Expanding Texture Atlas",
    "Enabling XMP Profiles",
    "Deploying Custom Fonts",
    "Authenticating Graphics ID",
    "Syncing System Clock",
    "Provisioning Update Server",
    "Updating Licensing Core",
    "Initializing RGB Controller",
    "Applying System Hotfix",
    "Rebuilding Rasterizer Table",
    "Generating Tesselation Map",
    "Resetting Power Profile",
    "Linking CUDA Extension",
    "Polling Fan Sensors",
    "Configuring Frame Queue",
    "Optimizing Flip Queue",
    "Scanning PCI Devices",
    "Migrating Render Context",
    "Injecting UX Layer",
    "Flushing Bitstream Cache",
    "Starting UI Renderer",
    "Assigning Thread Affinity",
    "Rewriting Render Tree",
    "Compiling HLSL Module",
    "Loading HDR Tables",
    "Bootstrapping Render Clock",
    "Scaling Driver Stack",
    "Starting Debug Interface",
    "Compiling SSAO Filter",
    "Applying Shadow Patch",
    "Resetting Display Flags",
    "Compressing Vertex Buffer",
    "Finalizing Installation"
]

